import postgres from 'postgres'
import type { MarketplaceAdminSkillSummary, MarketplaceAdminVersionSummary, MarketplaceAuditEntry, MarketplaceSkillStatus } from '@proma/shared'
import { SubmissionError } from '../submissions/submission-service.ts'

export class AdminManagementService {
  private readonly sql: postgres.Sql
  constructor(databaseUrl: string) { this.sql = postgres(databaseUrl) }
  async listSkills(query?: string): Promise<MarketplaceAdminSkillSummary[]> { const pattern = query?.trim() ? `%${query.trim()}%` : undefined; const rows = await this.sql<Array<{ id:string;slug:string;display_name:string;author_handle:string;category_slug:string;version:string;status:MarketplaceSkillStatus;install_count:number;updated_at:Date }>>`SELECT s.id,s.slug,s.display_name,a.handle author_handle,s.category_slug,v.version,v.status,s.install_count,s.updated_at FROM marketplace_skills s JOIN marketplace_authors a ON a.id=s.author_id JOIN marketplace_versions v ON v.id=s.latest_published_version_id WHERE ${pattern ? this.sql`(s.slug ILIKE ${pattern} OR s.display_name ILIKE ${pattern} OR a.handle ILIKE ${pattern})` : this.sql`true`} ORDER BY s.updated_at DESC`; return rows.map((row) => ({ id:row.id,slug:row.slug,displayName:row.display_name,authorHandle:row.author_handle,category:row.category_slug,version:row.version,status:row.status,installCount:Number(row.install_count),updatedAt:row.updated_at.toISOString() })) }
  async listVersions(skillId:string): Promise<MarketplaceAdminVersionSummary[]> { const rows=await this.sql<Array<{id:string;version:string;status:MarketplaceSkillStatus;sha256:string;created_at:Date;published_at:Date|null}>>`SELECT id,version,status,sha256,created_at,published_at FROM marketplace_versions WHERE skill_id=${skillId} ORDER BY created_at DESC`; return rows.map((row)=>({id:row.id,version:row.version,status:row.status,sha256:row.sha256,createdAt:row.created_at.toISOString(),...(row.published_at?{publishedAt:row.published_at.toISOString()}: {})})) }
  async lifecycle(skillId:string, action:'unlist'|'republish'|'archive', reason:string, actor:string):Promise<void>{ if(!reason.trim()) throw new SubmissionError('VALIDATION_FAILED','操作原因不能为空',400); await this.sql.begin(async(tx)=>{ const rows=await tx<{latest_published_version_id:string|null}[]>`SELECT latest_published_version_id FROM marketplace_skills WHERE id=${skillId} FOR UPDATE`; const versionId=rows[0]?.latest_published_version_id; if(!versionId) throw new SubmissionError('SKILL_NOT_FOUND','找不到该 Skill',404); const status=action==='republish'?'published':action==='unlist'?'unlisted':'archived'; await tx`UPDATE marketplace_versions SET status=${status} WHERE id=${versionId}`; if(action!=='republish') await tx`UPDATE marketplace_skills SET latest_published_version_id=null,updated_at=now() WHERE id=${skillId}`; await tx`INSERT INTO marketplace_audit_logs(actor,action,skill_id,details) VALUES(${actor},${`skill.${action}`},${skillId},${tx.json({reason:reason.trim()})})` }) }
  async audit(skillId?:string):Promise<MarketplaceAuditEntry[]>{ const rows=await this.sql<Array<{id:string;actor:string;action:string;skill_id:string|null;details:unknown;created_at:Date}>>`SELECT id,actor,action,skill_id,details,created_at FROM marketplace_audit_logs WHERE ${skillId?this.sql`skill_id=${skillId}`:this.sql`true`} ORDER BY created_at DESC LIMIT 200`; return rows.map((row)=>({id:row.id,actor:row.actor,action:row.action,...(row.skill_id?{skillId:row.skill_id}:{}),...(record(row.details)?{details:record(row.details)}:{}),createdAt:row.created_at.toISOString()})) }
}
function record(value:unknown):Record<string,unknown>|undefined{return typeof value==='object'&&value!==null&&!Array.isArray(value)?value as Record<string,unknown>:undefined}
